# Generated by Django 4.1.5 on 2023-01-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thread', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('message', models.CharField(max_length=255)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.thread')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
        ),
    ]
