# Generated by Django 4.1.5 on 2023-01-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
    ]
